## Сингулярное разложение матриц

#### Задание №1
Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
A

array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

In [7]:
np.set_printoptions(precision=2, suppress=True)

In [8]:
U, s, W = np.linalg.svd(A)

In [9]:
V = W.T

In [12]:
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [14]:
print(f'Матрица D:\n{D}')
print(f'Матрица U:\n{U}')
print(f'Матрица V:\n{V}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [11]:
np.dot(U.T,U)

array([[ 1., -0.,  0.,  0.,  0.],
       [-0.,  1., -0., -0., -0.],
       [ 0., -0.,  1., -0., -0.],
       [ 0., -0., -0.,  1., -0.],
       [ 0., -0., -0., -0.,  1.]])

In [15]:
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2. -0.]
 [-0.  0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [ 0.  1.  0.]]


#### Задание №2
Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

$a)$ __евклидову норму__

In [16]:
np.linalg.norm(A, ord=2)

8.824868854820442

$\left \| A \right \|_{E} = 8.82$

$б)$ __норму Фробениуса__

In [17]:
np.linalg.norm(A, ord='fro')

11.045361017187261

In [18]:
s

array([8.82, 6.14, 2.53])

$\left \| A \right \|_{F}=\sqrt{8.82^2 + 6.14 ^2 + 2.53^2} = 11.04$