## Матрицы и матричные операции. Часть 1¶

#### Задание №1.
Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

__Произвести умножение матрицы А на В и B на А невозможно, так как количество столбцов матрицы А не равно количеству строк матрицы В.__

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

__Если умножить матрицу A на матрицу B, будет матрица размерностью 2х3. Матрицу B умножить на матриу А нельзя, так как количество столбцов матрицы А не равно количеству строк матрицы В.__

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

__Умножение матрицы A на матрицу B, даёт матрицу размерностью 8х8. При умножени матрицы B на матрицу А, размерность матрицы составит 3х3__

г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

__Умножение матрицы A на матрицу B, даёт матрицу размерностью 4х4. При умножени матрицы B на матрицу А, размерность матрицы составит 4х4__

#### Задание №2.
Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [1]:
import numpy as np

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

$$A + B = 
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1 + 4 & -2 + (-1) \\
3 + 0 & 0 + 5
\end{pmatrix} = \begin{pmatrix}
5 & -3 \\
3 & 5
\end{pmatrix}
$$

In [8]:
print(f'Матрица A + B =\n{A + B}')

Матрица A + B
[[ 5 -3]
 [ 3  5]]


$$A \times B = 
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \times \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1 \cdot 4 + (-2) \cdot 0 & 1 \cdot (-1) + (-2) \cdot 5 \\
3 \cdot (4) + 0 \cdot 0 & 3 \cdot (-1) + 0 \cdot 5
\end{pmatrix} = \begin{pmatrix}
4 & -11 \\
12 & -3
\end{pmatrix}
$$

In [9]:
print(f'Матрица A x B =\n{np.dot(A, B)}')

Матрица A x B =
[[  4 -11]
 [ 12  -3]]


$$B \times A = 
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} \times \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} = \begin{pmatrix}
4 \cdot 1 + (-1) \cdot 3 & 4 \cdot (-2) + (-1) \cdot 0 \\
0 \cdot 1 + 5 \cdot 3 & 0 \cdot (-2) + 5 \cdot 0
\end{pmatrix} = \begin{pmatrix}
1 & -8 \\
15 & 0
\end{pmatrix}
$$

In [10]:
print(f'Матрица B x A =\n{np.dot(B, A)}')

Матрица B x A =
[[ 1 -8]
 [15  0]]


#### Задание №3.
Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$$3A = 3 \times \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} = \begin{pmatrix} 
3 \cdot 1 & 3 \cdot 7\\
3 \cdot 3 & 3 \cdot (-6)
\end{pmatrix} = \begin{pmatrix} 
3 & 21\\
9 & -18
\end{pmatrix}
$$

$$2B = 2 \times \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} = \begin{pmatrix} 
2 \cdot 0 & 2 \cdot 5\\
2 \cdot 2 & 2 \cdot (-1)
\end{pmatrix} = \begin{pmatrix} 
0 & 10\\
4 & -2
\end{pmatrix}
$$

$$4C = 4 \times \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix} 
4 \cdot 2 & 4 \cdot (-4)\\
4 \cdot 1 & 4 \cdot 1
\end{pmatrix} = \begin{pmatrix} 
8 & -16\\
4 & 4
\end{pmatrix}
$$

$$3A-2B+4C = \begin{pmatrix} 
3 - 0 + 8 & 21 - 10 - 16\\
9 - 4 + 4 & -18 - (-2) + 4
\end{pmatrix} = \begin{pmatrix} 
11 & -5 \\
9 & -12
\end{pmatrix}  
$$

In [16]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Матрица 3A - 2B + 4C =\n{3*A - 2*B + 4*C}')

Матрица 3A - 2B + 4C =
[[ 11  -5]
 [  9 -12]]


#### Задание №4.
Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [17]:
A = np.array([[4, 1], [5, -2], [2, 3]])

$AA^{T}=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
16 + 1 & 20 - 2 & 8 + 3\\ 
20 - 2 & 25 + 4 & 10 - 6\\ 
8 + 3 & 10 - 6 & 4 + 9
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}$

In [18]:
print(f'Матрица A * A^T =\n{np.dot(A, A.T)}')

Матрица A * A^T =
[[17 18 11]
 [18 29  4]
 [11  4 13]]


$A^{T}A = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix}
16 + 25 + 4 & 4 - 10 + 6\\ 
4 - 10 + 6 & 1 + 4 + 9
\end{pmatrix} = \begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$

In [19]:
print(f'Матрица A * A^T =\n{np.dot(A.T, A)}')

Матрица A * A^T =
[[45  0]
 [ 0 14]]


#### Задание №5.
Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [45]:
def matrix_mult(A,B):
    r = []
    m = []
    for i in range(len(A)):
        for j in range(len(B[0])):
            sums=0
            for k in range(len(B)):
                sums=sums+(A[i][k] * B[k][j])
            r.append(sums)
        m.append(r)
        r = []
    return m

##### Проведем эксперемент. Посчитаем скорость вычисления перемножения 2-х матриц библиотекой numpy и нашей функцией. Поможет нам в этом магическая команда %%timeit - запускает переданный ей код 100000 раз (по умолчанию) и выводит информацию среднем значении трех наиболее быстрых прогонах.

In [46]:
a = np.array([[2, 3, 8, 9], [5, 3, 4, 6], [5, 2, 4, 3], [5, 5, 5, 5], [4, 6, 7, 2], [1, 7, 2, 4], [3, 5, 0, 0]])
b = np.array([[2, 3, 1, 5, 1, 2, 8], [9, 5, 0, 1, 2, 3, 5], [6, 4, 5, 6, 7, 1, 5], [3, 4, 8, 9, 6, 4, 2]])

In [47]:
a.shape

(7, 4)

In [48]:
b.shape

(4, 7)

In [49]:
%%timeit
np.dot(a, b)

1.46 µs ± 4.69 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [50]:
np.dot(a, b)

array([[106,  89, 114, 142, 118,  57,  89],
       [ 79,  70,  73, 106,  75,  47,  87],
       [ 61,  53,  49,  78,  55,  32,  76],
       [100,  80,  70, 105,  80,  50, 100],
       [110,  78,  55,  86,  77,  41, 101],
       [ 89,  62,  43,  60,  53,  41,  61],
       [ 51,  34,   3,  20,  13,  21,  49]])

In [51]:
%%timeit
matmult(a, b)

188 µs ± 1.14 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [52]:
matmult(a, b)

[[106, 89, 114, 142, 118, 57, 89],
 [79, 70, 73, 106, 75, 47, 87],
 [61, 53, 49, 78, 55, 32, 76],
 [100, 80, 70, 105, 80, 50, 100],
 [110, 78, 55, 86, 77, 41, 101],
 [89, 62, 43, 60, 53, 41, 61],
 [51, 34, 3, 20, 13, 21, 49]]

## Матрицы и матричные операции. Часть 2

#### Задание №1.
Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

### а)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sinx \cdot sinx + cosx \cdot cosx = sin^2x +  cos^2x = 1$$

### б)
У нас матрица треугольного вида, определитель которой равен произведению диагональных элементов:
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4 \cdot 5 \cdot 9 = 180$$

In [56]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Определитель: {np.linalg.det(A):.0f}')

Определитель: 180


### в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = ({1}\cdot{5}\cdot{9} + {2}\cdot{6}\cdot{7} + {4}\cdot{8}\cdot{3}) - ({7}\cdot{5}\cdot{3} + {4}\cdot{2}\cdot{9} + {8}\cdot{6}\cdot{1}) = 225 - 225 = 0$$

In [55]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Определитель: {np.linalg.det(A):.0f}')

Определитель: 0


#### Задание №2.
Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) $det(A^{2}) = det(A \cdot A) = det(A) \cdot det(A) = 4 \cdot 4 = 16$;

б) $det(A^{T})= det(A) = 4$;

в) $det(2A) = 2^n \cdot det(A) = 2^n \cdot 4$, где $n$ размер матрицы.

#### Задание №3.
Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Матрица называется сингулярной, или вырожденной, если ее определитель равен нулю. Найдем определитель нашей матрицы.

$$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} = -2 \cdot 
\begin{vmatrix} 
-14 & 6 \\
 7 & 13 
\end{vmatrix} - 7 \cdot 
\begin{vmatrix} 
4 & 6 \\
-3 & 13
\end{vmatrix} + (-3) \cdot 
\begin{vmatrix} 
4 & -14 \\
7 & 13
\end{vmatrix} =$$

$$= -2 \cdot (-14 \cdot 13 - 6 \cdot 7) - 7 (4 \cdot 13 - 6 \cdot (-3)) + (-3)\cdot (4 \cdot 7 - (-14)\cdot (-3)) = 0$$

In [57]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Определитель: {np.linalg.det(A):.0f}')

Определитель: 0


#### Задание №4.
Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

а) отбросим 3 строку, т.к. это сумма 1 и 2. В получившейся матрице 1 и 2 строка линейно не зависят друг от друга, значит ранг 2. 

In [58]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

print(f'Ранг матрицы: {np.linalg.matrix_rank(A)}')

Ранг матрицы: 2


б) отбросим 3 строку, т.к. это сумма 1 и 2. В получившейся матрице остальные строки линейно не зависят друг от друга, значит ранг 3.

In [60]:
A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

print(f'Ранг матрицы: {np.linalg.matrix_rank(A)}')

Ранг матрицы: 3
