## Линейные преобразования

### Задание №1
Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

In [2]:
import numpy as np

Вычислим характеристический многочлен линейного оператора:

$$det(\textbf{A}-\lambda\textbf{I})$$

$$det(\textbf{A}-\lambda\textbf{I})=\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = \lambda^{2}-(-1 + 6)\lambda+(-6 + 12)= \lambda^{2} - 5\lambda + 6$$

Вычислим корни уравнения $\lambda^{2} - 5\lambda + 6$

$x_1 = 2, x_2 = 3$

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$

$\lambda = 2$

$\begin{cases}
-x_{1}-6x_{2} = 2x_{1}\\
2x_{1}+6x_{2} = 2x_{2}
\end{cases}$
$\begin{cases}
3x_{1} = -6x_{2}\\
2x_{2} = -x_{1}
\end{cases}$
$\begin{cases}
x_{1} = -2x_{2}\\
2x_{2} = -x_{1}
\end{cases}$
$\begin{cases}
x_{1} = -2\\
x_{2} = 1 
\end{cases}$

v1 = (-2, 1)

$\lambda = 3$

$\begin{cases}
-x_{1}-6x_{2} = 3x_{1}\\
2x_{1}+6x_{2} = 3x_{2}
\end{cases}$
$\begin{cases}
4x_{1} = -6x_{2}\\
2x_{1} = -3x_{2}
\end{cases}$
$\begin{cases}
x_{1} = -\frac{3}{2}x_{2}\\
x_{1} = -\frac{3}{2}x_{2}
\end{cases}$
$\begin{cases}
x_{1} = \frac{3}{2}\\
x_{2} = -1
\end{cases}$

v2 = ($\frac{3}{2}$, -1)

In [3]:
A = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


### Задание №2
Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

Возьмем вектор  $x=(4,3)$

$
\begin{pmatrix}
-1 & 0\\
0 & -1
\end{pmatrix}\cdot
\begin{pmatrix}
4\\
3
\end{pmatrix}=\lambda
\begin{pmatrix}
4\\
3
\end{pmatrix}
$

$
\begin{cases}
-4 = \lambda4\\
-3 = \lambda3
\end{cases}\Rightarrow
\lambda = -1
$

Собственное значение вектора является -1, отсюда следует, что равенсто будет верно при любых х. Поэтому, любой вектор является собственным.

In [4]:
A = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


### Задание №3
Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$x=(1,1)$

$
\begin{pmatrix}
1 & 1\\
-1 & 3
\end{pmatrix}\cdot
\begin{pmatrix}
1\\
1
\end{pmatrix}=\lambda
\begin{pmatrix}
1\\
1
\end{pmatrix}
$

$
\begin{cases}
2 = \lambda\\
-1+3 = \lambda
\end{cases}
\begin{cases}
2 = \lambda\\
2 = \lambda
\end{cases}\Rightarrow
\lambda = 2
$

Вектор $x=(1,1)$ является собственным вектором линейного оператора

In [6]:
A = np.array([[1, 1], 
              [-1, 3]])
x = np.array([1, 1])
l = np.dot(A, x)
l / x

array([2., 2.])

### Задание №4
Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix} \begin{pmatrix}
3 \\ 
-3\\
-4
\end{pmatrix} = \lambda \begin{pmatrix}
3 \\ 
-3\\
-4
\end{pmatrix}$$

$\begin{cases}
3\lambda=-9\\ 
-3\lambda=9\\
-4\lambda=-12
\end{cases}
$ $\Rightarrow
\begin{cases}
\lambda=-3\\ 
\lambda=-3\\
\lambda=3
\end{cases}$

Вектор $x=(3, -3, -4)$ не является собственным вектором линейного оператора A.

In [8]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
x = np.array([3, -3, -4])
l = np.dot(A, x)
l / x

array([-3., -3.,  3.])